# Generated by Django 3.2.5 on 2021-07-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
