# Generated by Django 3.2.5 on 2021-07-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
