# Generated by Django 3.2.5 on 2021-07-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
