# Generated by Django 3.2.5 on 2021-07-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_products'),
        ('orders', '0004_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Products'),
        ),
    ]
