# Generated by Django 3.2.5 on 2021-07-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_products'),
        ('orders', '0005_auto_20210708_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Products'),
        ),
    ]
